---
title: Sahil Ambardekar
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: 'null'
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: My Blog
google_verify: epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o
google_analytics: UA-XXXXXXX-X
author_name: Heiswayi Nrird
author_email: ambardekarsahil@gmail.com
author_gravatar: 2b38b1b0e7e08b69379bd61582adf0c8
baseurl: ''
permalink: "/notes/:title"
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: :compressed
include:
- robots.txt
exclude:
- LICENSE
- README.md
- CNAME
- vendor
- Gemfile
gems:
- jekyll-sitemap
compress_html:
  clippings: all
  ingore:
    envs:
    - test
